### ISSUE TITLE
Command 'avalonia.showPreviewToSide' not found

### ISSUE THREAD

**Issue by orange-pig** [AvaloniaUI/Avalonia-VSCode-Extension#4]
Avalonia for VSCode: v0.0.16
dotnet: 8.0.100-preview.7.23376.3
vscode version: 1.81.1

I am doing run demo project step by step. After build success,  click preview icon button, get the error message.

![image](https://github.com/AvaloniaUI/Avalonia-VSCode-Extension/assets/5195198/7f7ced87-4579-427c-8a53-78b280efd25c)

**Comment by prashantvc** [comment]
I believe the extension is not activated. Did you try restart the VS Code?

**Comment by orange-pig** [comment]
@prashantvc I do it, tried restart VSCode and reinstall extension. 
OS info:
windows10 profressional 22h2 19045.3393

**Comment by prashantvc** [comment]
> @prashantvc I do it, tried restart VSCode and reinstall extension.

Thanks, sounds like a bug to me. I will prioritise it for the next release :)

**Comment by philippun1** [comment]
Can confirm this issue also on Ubuntu 23.04:
Avalonia for VSCode: v0.0.16
dotnet: 6.0.116
vscode version: 1.81.1

**Comment by microhobby** [comment]
Hey guys, @philippun1 and @orange-pig , the LSP was compiled using dotnet 7. So, have dotnet 7 is a dependency. I was having the same issue, after installing the dotnet 7 it worked.

**Comment by prashantvc** [comment]
> dotnet: 6.0.116

@philippun1 
Could you try update to dotnet 7?

**Comment by philippun1** [comment]
@prashantvc It works with dotnet7, thanks for the hint.

**Comment by orange-pig** [comment]
@microhobby It open previewer success when I add the global.json specify sdk version with 7.0.400, thanks reminder！

**Comment by prashantvc** [comment]
I am going to close the issue, please reopen if you continue to have an issue
