### ISSUE TITLE
Previewer doesnt work

### ISSUE THREAD

**Issue by ArcadeArchie** [AvaloniaUI/Avalonia-VSCode-Extension#5]
when i try opening the previewer via the command palette i get this error: 
![image](https://github.com/AvaloniaUI/Avalonia-VSCode-Extension/assets/29282748/20facce5-19b8-46a1-8704-29b84860b748)

the code completion works as one would expect just the previewer doesn't

### Environment

```markdown
- VScode Version: 1.81.1 (user setup)
- Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Date: 2023-08-09T22:22:42.175Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.19045
- Extensions:
   - C# 2.0.416
   - C# Dev Kit 0.4.8
   - Avalonia for VSCode 0.0.16
   - IntelliCode for C# Dev Kit 0.1.26
```

**Comment by prashantvc** [comment]
That's odd, could you file a bug from VS Code’s Help > Report Issue dialog. So I can get the logs to debug.
Does restarting the VS Code help?

**Comment by ArcadeArchie** [comment]
it doesnt but the previewer is blank even after building the project

**Comment by ArcadeArchie** [comment]
here the bug infos
Type: <b>Bug</b>

1. Generate a blank Avalonia.MVVM project
2. Open it in VSCode
3. Open MainWindow.axaml
4. Open the Command palette
5. Execute 'Avalonia: Show preview to the side'

Extension version: 0.0.16
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.94GB free)|
|Process Argv|--crash-reporter-id 39705c0c-faf3-4dfe-89a2-37818e2551da|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by prashantvc** [comment]
I confirm this as a bug. For now please do not open previewer from the command palette. Open it using the previewer button on the XAML file tab

> it doesnt but the previewer is blank even after building the project

Switch to XAML file after you open the preview or save the file again

**Comment by ArcadeArchie** [comment]
also just noticed this the "Show preview" option in the context menu also doesn't work, it doesn't do anything. No error no nothing

**Comment by prashantvc** [comment]
@orange-pig can you try making a small change to the AXAML file and saving it.
Also share logs from Output window (shift + ctrl + U) and select Avalonia Client from the dropdown

**Comment by orange-pig** [comment]
Changing take some effect,  sometimes reopen Previewer blank still. the follow log come from work well and blank.
[work_well_log.txt](https://github.com/AvaloniaUI/Avalonia-VSCode-Extension/files/12480931/work_well_log.txt)
[blank_log.txt](https://github.com/AvaloniaUI/Avalonia-VSCode-Extension/files/12480932/blank_log.txt)
